//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsDust.Platform.Protocol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KsDust.Platform.Protocol.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ks_Dust.
        /// </summary>
        internal static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a01002-Avg.
        /// </summary>
        internal static string HUMIDITY {
            get {
                return ResourceManager.GetString("HUMIDITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a50001-Avg.
        /// </summary>
        internal static string NOISE {
            get {
                return ResourceManager.GetString("NOISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a34002-Avg.
        /// </summary>
        internal static string PM100 {
            get {
                return ResourceManager.GetString("PM100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a34004-Avg.
        /// </summary>
        internal static string PM25 {
            get {
                return ResourceManager.GetString("PM25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a01001-Avg.
        /// </summary>
        internal static string TEMPERATURE {
            get {
                return ResourceManager.GetString("TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a34001-Avg.
        /// </summary>
        internal static string TSP {
            get {
                return ResourceManager.GetString("TSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a01008-Avg.
        /// </summary>
        internal static string WINDDIRECTION {
            get {
                return ResourceManager.GetString("WINDDIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a01007-Avg.
        /// </summary>
        internal static string WINDSPEED {
            get {
                return ResourceManager.GetString("WINDSPEED", resourceCulture);
            }
        }
    }
}
