// <auto-generated />
namespace Dust.Platform.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropColumnIsReaded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropColumnIsReaded));
        
        string IMigrationMetadata.Id
        {
            get { return "201703280703213_DropColumnIsReaded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
