// <auto-generated />
namespace Dust.Platform.Storage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddColumn_StatisticsToTableOnlineStatistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumn_StatisticsToTableOnlineStatistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201702170530269_AddColumn_StatisticsToTableOnlineStatistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
